name: stanza_scrapper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  desktop_webview_window: ^0.2.3
  elevenlabs_flutter:
    path: ../elevenlabs_flutter
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  path: ^1.8.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
  build_windows: flutter build windows --release -t lib/main.dart

flutter:
  uses-material-design: true
