name: stanza_scrapper
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  collection: ^1.18.0
  desktop_webview_window: ^0.2.3
  either_dart: ^1.0.0
  eleven_labs:
    path: ./packages/eleven_labs
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.2
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  package_info_plus: ^8.1.1
  path: ^1.8.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
  build_windows: flutter build windows --release -t lib/main.dart

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/